spring:
  datasource:
    url: jdbc:postgresql://monorail.proxy.rlwy.net:45543/railway
    username: postgres
    password: zhjHzyoYSLWmAjDlIfcbMGjQpqbnIsXu
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
